In [97]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split, cross_val_score
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import RidgeCV

%matplotlib inline

In [98]:
#Bring in the data

nba = pd.read_csv('./data/nba_analysis_data.csv')
nba.dropna(inplace = True)

In [99]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9131 entries, 0 to 9130
Data columns (total 35 columns):
cover                    9131 non-null int64
line_cv                  9131 non-null float64
eff_ratio                9131 non-null float64
eff_ratio2               9131 non-null float64
away_rest                9131 non-null int64
main_referee             9131 non-null int64
home_rest                9131 non-null int64
ref_2                    9131 non-null int64
ref_3                    9131 non-null int64
spread                   9131 non-null float64
home_win_margin          9131 non-null float64
mov_5_fta                9131 non-null float64
mov_5_away_fta           9131 non-null float64
free_throw_ratio         9131 non-null float64
mov_5_home_score         9131 non-null float64
mov_5_away_score         9131 non-null float64
score_ratio              9131 non-null float64
rebound_ratio            9131 non-null float64
mov_5_tot                9131 non-null float64
mov_5_away_t

In [100]:
features = ['eff_ratio', 'mov_5_fta', 'mov_5_away_fta',  
            'eff_ratio2', 'away_rest', 
            'home_rest', 
            'free_throw_ratio', 'spread',
            'score_ratio', 'mov_5_home_score', 'mov_5_away_score',
            'mov_5_away_off_eff', 'mov_5_away_def_eff', 
            'mov_5_away_assists', 'mov_5_home_win_margin',
            'mov_5_win', 'mov_5_away_win_margin', 'home_win_pct', 'away_win_pct',
            'high_alt', 'home_ave_win_margin', 'away_ave_win_margin',
            'playoff_game']
X = nba[features]
y = nba['home_win_margin']

In [101]:
#splitting data for a train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y , 
                                                    random_state = 4)

In [102]:
#scaling data to use in various other methods
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

/Users/bryancombs/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/bryancombs/anaconda3/lib/python3.6/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/Users/bryancombs/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [292]:
rf = RandomForestRegressor()
rf_params = {'n_estimators'      : [400,500, 600, 700],
             'max_depth'         : [ 60, 70, 80, 90 ],
             'min_samples_split' : [8,11, 14, 17, 22  ]
            }

In [293]:
gs = GridSearchCV(rf, param_grid= rf_params)

In [ ]:
gs.fit(X_train_scaled,y_train)

/Users/bryancombs/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [ ]:
gs.best_score_

In [ ]:
gs.best_params_

In [ ]:
gs.score(X_test_scaled, y_test)

In [ ]:
y_hat_rf = gs.predict(X_test_scaled)

In [ ]:
y_hat_rf

In [ ]:
rr = RidgeCV(alphas = [100, 150, 80])


In [ ]:
rr.fit(X_train_scaled, y_train);

In [ ]:
rr.score(X_train_scaled, y_train)

In [ ]:
rr.score(X_test_scaled, y_test)

In [270]:
rr.coef_


array([ 3.77482651e-02,  3.07225977e-01, -5.09244140e-02,  2.23296882e-02,
        4.85549294e-01, -3.96244640e-01, -2.06696422e-01, -5.22718224e+00,
       -9.03454808e-02,  3.81684471e-04,  1.99110037e-01,  4.01191365e-01,
       -3.00354135e-01, -2.52802711e-01,  5.16840772e-01, -9.55835732e-01,
       -3.80399186e-01,  2.35863742e-01,  6.84559268e-01,  1.75960327e-01,
        9.35199379e-01, -1.10179319e+00,  3.61978133e-02])

In [271]:
y_hat_rr = rr.predict(X_test_scaled)

In [272]:
rr.alpha_

100

In [273]:
y_hat_rr

array([ 1.75688512, -1.89108177, 12.70695595, ...,  4.20378938,
       11.13123548,  2.09339121])

In [119]:
svm = SVR(kernel="linear", C = 5)


In [120]:
svm.fit(X_train_scaled,y_train)

SVR(C=5, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [121]:
svm.score(X_train_scaled, y_train)

0.2148030883256683

In [122]:
svm.score(X_test_scaled, y_test)

0.20615428938410918

In [123]:
y_hat_svm = svm.predict(X_test_scaled)
y_hat_svm

array([ 1.37110751, -1.78489493, 12.81406217, ...,  3.47352254,
       11.08402482,  1.95221682])

### Neural Network

Going to fit a neural network with the X features.   I am not concerned about inference.  Accurate prediction is all that matters.  So am going to set up an neural network as one of the final predictors of Home Win Margin.

In [124]:
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

In [125]:
model = Sequential()
model.add(Dense(23, 
                activation = 'relu',
                input_dim = X_train.shape[1]))
model.add(Dense(7, activation = 'relu'))

model.add(Dense(1, activation = None)) #output layer 

In [126]:
model.compile(loss = 'mean_squared_error', optimizer='adam' )
model.fit(X_train_scaled, 
          y_train, epochs = 40, 
          batch_size= 32, 
          validation_data=(X_test_scaled, y_test))

Train on 6848 samples, validate on 2283 samples
Epoch 1/70
6848/6848 [==============================] - 1s 77us/step - loss: 163.0110 - val_loss: 151.7636
Epoch 2/70
6848/6848 [==============================] - 0s 41us/step - loss: 148.2062 - val_loss: 145.8358
Epoch 3/70
6848/6848 [==============================] - 0s 38us/step - loss: 143.9654 - val_loss: 143.2724
Epoch 4/70
6848/6848 [==============================] - 0s 34us/step - loss: 141.4566 - val_loss: 141.9561
Epoch 5/70
6848/6848 [==============================] - 0s 31us/step - loss: 139.9267 - val_loss: 141.1182
Epoch 6/70
6848/6848 [==============================] - 0s 38us/step - loss: 138.8562 - val_loss: 140.7126
Epoch 7/70
6848/6848 [==============================] - 0s 42us/step - loss: 138.2174 - val_loss: 140.4813
Epoch 8/70
6848/6848 [==============================] - 0s 40us/step - loss: 137.6911 - val_loss: 140.2278
Epoch 9/70
6848/6848 [==============================] - 0s 37us/step - loss: 137.2566 - val_loss

In [127]:
y_hat_nn = model.predict(X_test_scaled)
predictions = pd.DataFrame(y_hat_nn, columns= ['y_hat_nn'])
predictions

y_hat_nn
0      3.944405
1     -4.357571
2     11.830326
3      6.192354
4      1.581554
5     15.581586
6      8.221266
7      2.618827
8      4.615789
9      6.315024
10    -2.372210
11    10.261059
12     5.360137
13   -11.327173
14    -0.386334
15     1.841667
16     4.448718
17     4.926818
18    -2.901725
19    -7.417709
20     7.204742
21    10.125046
22     8.746824
23     6.397998
24    -5.497104
25     5.043386
26    -0.133429
27     4.737046
28     6.598379
29     4.295778
...         ...
2253  14.352613
2254   7.538024
2255   7.463308
2256   5.222723
2257   2.909728
2258   6.068295
2259  15.778423
2260  10.063038
2261   7.799672
2262   2.248380
2263   5.411664
2264   5.721120
2265  -1.669966
2266  16.977446
2267   4.511625
2268   1.606575
2269   4.615746
2270  -5.278851
2271   7.156647
2272  -0.299443
2273  -7.565031
2274   0.563565
2275 -12.758967
2276   6.162061
2277   4.459467
2278  -4.178605
2279  -3.848452
2280   5.764909
2281   8.048155
2282   1.982425

[2283 rows x 1 columns]

In [276]:
predictions['y_hat_rr'] = y_hat_rr
predictions['y_hat_svm'] = y_hat_svm
predictions['y_hat_rf'] = y_hat_rf


In [277]:
predictions.head(10)

y_hat_nn   y_hat_rr  y_hat_svm   y_hat_rf  y_test  spread  y_hat_ave  \
0   3.944405   1.756885   1.371108  -0.600012    -1.0    -1.5   3.171716   
1  -4.357571  -1.891082  -1.784895  -1.091522    -8.0     1.0  -3.568923   
2  11.830326  12.706956  12.814062  11.736707     6.0   -13.5  12.059877   
3   6.192354   5.395059   5.354332   5.394062    -5.0    -7.0   5.907983   
4   1.581554   2.674261   2.352306   3.691513     8.0    -3.5   1.953234   
5  15.581586  17.647940  17.578159  19.273758     9.0   -15.5  16.241839   
6   8.221266   8.361175   9.815642   6.323641    14.0   -10.0   8.438949   
7   2.618827   0.846593   0.339522   0.640337    -9.0    -1.0   2.075854   
8   4.615789   3.247947   3.114539   2.831380     5.0    -4.5   4.165951   
9   6.315024   4.362554   4.104572   4.636746    -6.0    -3.5   5.592544   

   predict_svm  predict_rr  predict_nn  actual  predict  
0            0           1           1       0        3  
1            0           0           0       0        0  
2            0           0           0       0        0  
3            0           0           0       0        0  
4            0           0           0       1        0  
5            1           1           1       0        4  
6            0           0           0       1        0  
7            0           0           1       0        1  
8            0           0           1       1        1  
9            1           1           1       0        4

In [278]:
y_s = pd.DataFrame(y_test)
y_s.reset_index(inplace = True)
predictions['y_test'] = y_s['home_win_margin']
predictions.head()

y_hat_nn   y_hat_rr  y_hat_svm   y_hat_rf  y_test  spread  y_hat_ave  \
0   3.944405   1.756885   1.371108  -0.600012    -1.0    -1.5   3.171716   
1  -4.357571  -1.891082  -1.784895  -1.091522    -8.0     1.0  -3.568923   
2  11.830326  12.706956  12.814062  11.736707     6.0   -13.5  12.059877   
3   6.192354   5.395059   5.354332   5.394062    -5.0    -7.0   5.907983   
4   1.581554   2.674261   2.352306   3.691513     8.0    -3.5   1.953234   

   predict_svm  predict_rr  predict_nn  actual  predict  
0            0           1           1       0        3  
1            0           0           0       0        0  
2            0           0           0       0        0  
3            0           0           0       0        0  
4            0           0           0       1        0

In [279]:
X_spread = pd.DataFrame(X_test)
X_spread.reset_index(inplace = True)
predictions['spread'] = X_spread['spread']
predictions.head()

y_hat_nn   y_hat_rr  y_hat_svm   y_hat_rf  y_test  spread  y_hat_ave  \
0   3.944405   1.756885   1.371108  -0.600012    -1.0    -1.5   3.171716   
1  -4.357571  -1.891082  -1.784895  -1.091522    -8.0     1.0  -3.568923   
2  11.830326  12.706956  12.814062  11.736707     6.0   -13.5  12.059877   
3   6.192354   5.395059   5.354332   5.394062    -5.0    -7.0   5.907983   
4   1.581554   2.674261   2.352306   3.691513     8.0    -3.5   1.953234   

   predict_svm  predict_rr  predict_nn  actual  predict  
0            0           1           1       0        3  
1            0           0           0       0        0  
2            0           0           0       0        0  
3            0           0           0       0        0  
4            0           0           0       1        0

In [280]:
y_test

4741    -1.0
6253    -8.0
1166     6.0
6353    -5.0
3631     8.0
1646     9.0
9075    14.0
7345    -9.0
4677     5.0
2703    -6.0
8031     1.0
6450    32.0
387     13.0
6636    -9.0
8119     3.0
758     14.0
9108     8.0
3030     3.0
4452   -17.0
4273    -4.0
4887     3.0
3715    18.0
2323     7.0
7775     3.0
5773    -7.0
2031     5.0
4134    10.0
2719    20.0
3281     5.0
186     -2.0
        ... 
5213     3.0
3550     7.0
5427    -8.0
3549     3.0
8560    11.0
2672    -8.0
2538    13.0
6074    15.0
8406    11.0
7695     8.0
4130     9.0
316     13.0
9060    -2.0
528     18.0
7361    23.0
307      4.0
4994    25.0
7265     3.0
13       7.0
4542    -4.0
2576   -11.0
8666    -3.0
3466    -7.0
2168   -11.0
6915     2.0
4402     7.0
2975    -5.0
3245     5.0
3       -2.0
7630   -28.0
Name: home_win_margin, Length: 2283, dtype: float64

In [281]:
predictions['y_hat_ave'] = (predictions.y_hat_nn + 
                           
                            predictions.y_hat_rr + 
                            predictions.y_hat_nn)/3

In [282]:
predictions.head(20)

y_hat_nn   y_hat_rr  y_hat_svm   y_hat_rf  y_test  spread  y_hat_ave  \
0    3.944405   1.756885   1.371108  -0.600012    -1.0    -1.5   3.215232   
1   -4.357571  -1.891082  -1.784895  -1.091522    -8.0     1.0  -3.535408   
2   11.830326  12.706956  12.814062  11.736707     6.0   -13.5  12.122536   
3    6.192354   5.395059   5.354332   5.394062    -5.0    -7.0   5.926589   
4    1.581554   2.674261   2.352306   3.691513     8.0    -3.5   1.945790   
5   15.581586  17.647940  17.578159  19.273758     9.0   -15.5  16.270370   
6    8.221266   8.361175   9.815642   6.323641    14.0   -10.0   8.267902   
7    2.618827   0.846593   0.339522   0.640337    -9.0    -1.0   2.028083   
8    4.615789   3.247947   3.114539   2.831380     5.0    -4.5   4.159842   
9    6.315024   4.362554   4.104572   4.636746    -6.0    -3.5   5.664200   
10  -2.372210  -2.282687  -2.220582   0.515377     1.0     2.5  -2.342369   
11  10.261059   9.842733   9.317405  10.193635    32.0    -8.5  10.121617   
12   5.360137   4.597203   4.329849   0.571312    13.0    -3.5   5.105826   
13 -11.327173  -8.768830  -9.460638  -6.025494    -9.0     8.0 -10.474392   
14  -0.386334   1.891665   2.359538   3.622575     3.0    -4.0   0.372999   
15   1.841667   2.236160   2.090219   0.461259    14.0    -2.0   1.973165   
16   4.448718   5.487984   5.709842   4.172201     8.0    -5.0   4.795140   
17   4.926818   5.042570   4.961144   3.824181     3.0    -5.0   4.965402   
18  -2.901725  -5.724458  -6.303604  -5.206017   -17.0     4.5  -3.842636   
19  -7.417709 -10.472332 -11.349549  -5.429572    -4.0     7.5  -8.435917   

    predict_svm  predict_rr  predict_nn  actual  predict  
0             0           1           1       0        3  
1             0           0           0       0        0  
2             0           0           0       0        0  
3             0           0           0       0        0  
4             0           0           0       1        0  
5             1           1           1       0        4  
6             0           0           0       1        0  
7             0           0           1       0        1  
8             0           0           1       1        1  
9             1           1           1       0        4  
10            1           1           1       1        4  
11            1           1           1       1        4  
12            1           1           1       1        4  
13            0           0           0       0        0  
14            0           0           0       0        0  
15            1           1           0       1        3  
16            1           1           0       1        3  
17            0           0           0       0        0  
18            0           0           1       0        1  
19            0           0           1       1        1

In [283]:
predictions['predict_svm'] =  (predictions.y_hat_svm + X_test.spread).map(
    lambda x: 0 if x <0 else 1)

In [284]:
predictions['predict_rr'] =  (predictions.y_hat_rr + X_test.spread).map(
    lambda x: 0 if x <0 else 1)

In [285]:
predictions['predict_nn'] =  (predictions.y_hat_nn + X_test.spread).map(
    lambda x: 0 if x <0 else 1)

In [286]:
predictions['actual'] = (predictions.y_test + predictions.spread).map(lambda x: 0 if x< 0 else 1)

In [287]:
predictions['predict'] = (predictions['predict_svm']+ 
    predictions['predict_rr'] + predictions['predict_nn']+ 
                          predictions['predict_rr'])

In [288]:
print(classification_report(predictions.actual, predictions.predict))

              precision    recall  f1-score   support

           0       0.50      0.46      0.48      1119
           1       0.49      0.14      0.22      1164
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0

   micro avg       0.30      0.30      0.30      2283
   macro avg       0.20      0.12      0.14      2283
weighted avg       0.50      0.30      0.35      2283



/Users/bryancombs/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [289]:
confusion_matrix(X_test.actual, X_test.predict)

array([[768, 351],
       [769, 395]])

In [290]:
predictions.predict.value_counts(normalize = True)

0    0.448971
4    0.210688
1    0.146299
3    0.120894
2    0.073149
Name: predict, dtype: float64

In [291]:
predictions.groupby(['predict'])['actual'].mean()

predict
0    0.496585
1    0.491018
2    0.479042
3    0.539855
4    0.544699
Name: actual, dtype: float64